### ISSUE TITLE
docker: Error response from daemon: could not get container for some-squid: No such container: some-squid.

### ISSUE THREAD

**Issue by timsayshey** [justinschw/docker-squid-e2guardian-pi#2]
Here is the command I am running:

```
 docker run --name e2guardian-rpi -d --restart=always \
  --publish 3128:3128 \
  --volume /home/pi/e2guardian-lists:/etc/e2guardian/lists \
  --volume /home/pi/docker-squid/squid-conf:/etc/squid \
  --link some-squid:proxy \
  jusschwa/docker-squid-e2guardian-rpi:latest 
  ```
  
  And this is the error I am getting:
  ```
  docker: Error response from daemon: could not get container for some-squid: No such container: some-squid.
  ```

How do I resolve this issue?

**Comment by justinschw** [comment]
Is your squid proxy container already running? Also is there a reason you are wanting to link to another squid container? The point of this particular container image I created is to combine both squid and e2guardian into a single container, for simplicity and for security reasons. Anyways, if you really are wanting to link to another squid container, you need it to be running. I should mention that at the time I was developing this the --link command was on its way to deprecation. From what I understand, containers should be able to talk to each other without it.

If you are only including --link because it is in the readme, then it is just a copy paste error, go ahead and remove that. Sorry about that.

Eventually I want to start actively developing this again... when life gets less busy

⁣Get BlueMail for Android ​

**Comment by timsayshey** [comment]
Yeah, it seems like this has the potential to be a great tool. We're schooling from home and I'm wanting to setup a transparent proxy for more robust network parental controls.

I think the issue was that I don't have Squid or e2gaurdian running. I thought it was included.

It would be super helpful to just have a docker-compose.yml file in the repo.

**Comment by timsayshey** [comment]
I created the following docker-compose file below but I get the following error:
` standard_init_linux.go:219: exec user process caused: exec format error`

```e2guardianSquid:
  image: jusschwa/docker-squid-e2guardian-rpi
  ports:
    - "3128:3128"
  volumes:
    - ./e2guardian/lists:/etc/e2guardian/lists
    - ./squid/conf:/etc/squid
  restart: always
  ```
  
  Any ideas?

**Comment by timsayshey** [comment]
I updated the docker compose file to the following and pointed it to this repo instead of using the dockerhub image. However I get a new error when building:

```
# ... Errror
Step 8/39 : RUN apt-get update &&     apt-get -qq -y install openssl libssl1.0-dev build-essential wget curl net-tools dnsutils tcpdump dnsmasq &&     apt-get clean
 ---> [Warning] The requested image's platform (linux/arm) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in f3e552f6dd6b
standard_init_linux.go:219: exec user process caused: exec format error
ERROR: Service 'e2guardian-squid' failed to build : The command '/bin/sh -c apt-get update &&     apt-get -qq -y install openssl libssl1.0-dev build-essential wget curl net-tools dnsutils tcpdump dnsmasq &&     apt-get clean' returned a non-zero code: 1
```

```
# docker-compose.yml
version: '2'

services:
  e2guardian-squid:
    build:
      context: ./docker-squid-e2guardian-pi
      dockerfile: Dockerfile
    ports:
      - "3128:3128"
    volumes:
      - ./e2guardian/lists:/etc/e2guardian/lists
      - ./squid/conf:/etc/squid
    restart: always
```

**Comment by timsayshey** [comment]
I figured it out. It's because I switched from raspberry pi to popos on a desktop. I'm modifying a few things to get it working with my setup.
